# Profile to automatically install the latest `default.toml` from Github.
# You can remove the hash for easier updates, but this reduces security.

[[imports]]
src = "https://raw.githubusercontent.com/OgGhostJelly/ogj-ferium-profiles/refs/heads/main/default.toml"
hash = "f24a7e3f9e93a0174ed9f270ebb27c0200516231444dce7fb90a6c9bc19ed7f7af8bb692191ad453f4e2de38079772f57dc78fd7df132a4c5754c9930f5657f5"
